# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Arcane Reveries
# email: your-email@example.com
# description: >- # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://manikantareddyd.github.io" # the base hostname & protocol for your site, e.g. http://example.com
description: "This is about Mani, a developer, a curious mind and an amateur astronomer. I heard that you wanted to know me, so here you go."
# twitter_username: jekyllrb
keywords: "Arcane Reveries, Manikanta Reddy D"
collections:
  work:

email:              manikanta.reddy.d@outlook.com
twitter:            ManikantaReddyD
facebook:           Manikanta.D.Reddy
github:             ManikantaReddyD
stackoverflow:     6345500/manikanta-reddy-d
linkedin:          ManikantaDReddy
#xing:              username
#instagram:          username
lastfm:            ManikantaReddy
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
# youtube:           UCnwMLnk0Z61kFt3igpCkrvQ
soundcloud:        ManikantaReddyD
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
spotify: 12185478274
reddit: ManikantaReddyD
skype: manikanta.reddy.d


analytics:
  facebook: 1974458362838018

bing:
    validate: "10805F027940A5586DCE409A0027B30F"

disqus_shortname:   manikantareddyd

fbcomments: 1
fb_appid: 1166944040038372

remote_theme: broccolini/swiss
permalink: /blog/:title/
# Build settings
markdown: kramdown
theme: jekyll-swiss
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
