---
layout: post
title: "Two Partition"
date: 2018-11-05
excerpt: 'We show that the two partition problem is NP Complete.'
comments: true
mathjax: true
tags: algorithms complexity
feature: "/images/2018-11-05-npc-partition/main.png"
---
<p>We have <span class="math inline"><em>n</em></span> items each having a value <span class="math inline"><em>s</em><sub><em>i</em></sub></span>. We have to create two buckets(<span class="math inline"><em>A</em></span>, <span class="math inline"><em>B</em></span>) with all of the <span class="math inline"><em>n</em></span> items such that total value of first bucket is same as the second. We put some in <span class="math inline"><em>A</em></span> (<span class="math inline"><em>s</em><sub><em>a</em>1</sub>, ...<em>s</em><sub><em>a</em><em>x</em></sub></span>) and some in <span class="math inline"><em>B</em></span> (<span class="math inline"><em>s</em><sub><em>b</em>1</sub>, ..., <em>s</em><sub><em>b</em><em>y</em></sub></span>) then we have</p>
<p><br /><span class="math display">$$\sum_{k=1}^x s_{ak} = \sum_{k=1}^y s_{bk}$$</span><br /></p>
<p>We call this problem <span class="math inline">2-PARTITION(<em>2</em><em>P</em>)</span>, we are to show <span class="math inline"><em>2</em><em>P</em> ∈ NP-COMPLETE</span></p>
<h3 id="is-in-np"><span class="math inline"><em>2</em><em>P</em> ∈ <em>N</em><em>P</em></span></h3>
<p>Given any two arrangements of the items we can verify whether the sum of their values is equal. We’ll also have to verify if the items in first bucket are not there in the other and that all items are present in one or the other. This will require us to go through all the items, therefore the verification task is <span class="math inline"><em>O</em>(<em>n</em>)</span> a polynomial verification. Therefore <span class="math inline"><em>2</em><em>P</em> ∈ <em>N</em><em>P</em></span></p>
<h3 id="reduction">Reduction</h3>
<p>We pick up the SUBSET-SUM problem and show that it is easier than 2-PARTITION problem. The SUBSET-SUM problem goes as follows, Given non-negative weights <span class="math inline"><em>w</em><sub>1</sub>, …, <em>w</em><sub><em>n</em></sub></span> and an integer <span class="math inline"><em>W</em></span>, is there a subset that adds up to exactly <span class="math inline"><em>W</em></span>. We call SUBSET-SUM as <span class="math inline"><em>S</em><em>S</em></span>. We are to show <br /><span class="math display"><em>S</em><em>S</em>≤<sub><em>p</em></sub><em>2</em><em>P</em></span><br /></p>
<h3 id="inputs">Inputs</h3>
<p>An input to <span class="math inline"><em>S</em><em>S</em></span> is a set <span class="math inline"><em>X</em></span> of non-negative and an integer <span class="math inline"><em>W</em></span>. Consider a value <span class="math inline"><em>w</em>′=<em>s</em><em>u</em><em>m</em>(<em>X</em>)−2<em>W</em></span>. Make a set <span class="math inline"><em>X</em>′=<em>X</em> + <em>w</em>′</span> which correspond to value of items and ask <span class="math inline"><em>2</em><em>P</em></span> if <span class="math inline"><em>X</em>′</span> can be split into two buckets of equal total value (<span class="math inline"><em>s</em><em>u</em><em>m</em>(<em>X</em>)−<em>W</em></span>). This is a polynomial time input transformation.</p>
<h3 id="ssiyes-iff-isi"><span class="math inline"><em>S</em><em>S</em>(<em>i</em>)=<em>Y</em><em>E</em><em>S</em> ⇔ <em>2</em><em>P</em>(<em>i</em>)</span></h3>
<h4 id="ssiyes-implies-isi"><span class="math inline"><em>S</em><em>S</em>(<em>i</em>)=<em>Y</em><em>E</em><em>S</em> ⟹ <em>2</em><em>P</em>(<em>i</em>)</span></h4>
<p>There exists a subset of <span class="math inline"><em>X</em></span> of weight <span class="math inline"><em>W</em></span>, then the remaining elements in <span class="math inline"><em>X</em></span> will have a weight sum <span class="math inline">=<em>s</em><em>u</em><em>m</em>(<em>X</em>)−<em>W</em></span>. Therefore there is arrangement of items such that one of the buckets has a total value of <span class="math inline"><em>s</em><em>u</em><em>m</em>(<em>X</em>)−<em>W</em></span>, then definitely the other will have a total value of <span class="math inline"><em>s</em><em>u</em><em>m</em>(<em>X</em>)−<em>W</em></span> as the total total value is <span class="math inline">2(<em>s</em><em>u</em><em>m</em>(<em>X</em>)−<em>W</em>)</span>. Therefore we can partition the items into two buckets of same total value.</p>
<h4 id="ssiyes-impliedby-isi"><span class="math inline"><em>S</em><em>S</em>(<em>i</em>)=<em>Y</em><em>E</em><em>S</em> ⟸ <em>2</em><em>P</em>(<em>i</em>)</span></h4>
<p>We can split <span class="math inline"><em>X</em>′</span> into two buckets such that each has a total value of <span class="math inline"><em>s</em><em>u</em><em>m</em>(<em>X</em>′)/2 = <em>s</em><em>u</em><em>m</em>(<em>X</em>)−<em>W</em></span>. One of these buckets will contain a item of total value <span class="math inline"><em>w</em>′</span>. Discard that item, then the remaining items will have a total value <span class="math inline"><em>W</em></span>. Pick the elements corresponding to these items in <span class="math inline"><em>X</em></span>, then they are subset of <span class="math inline"><em>X</em></span> of weight <span class="math inline"><em>W</em></span>. Therefore there exists a subset of total weight <span class="math inline"><em>W</em></span> in <span class="math inline"><em>X</em></span>.</p>
<h3 id="is-in-textnp-complete"><span class="math inline"><em>2</em><em>P</em> ∈ NP-COMPLETE</span></h3>
<p>We have shown that <span class="math inline"><em>S</em><em>S</em>≤<sub><em>p</em></sub><em>2</em><em>P</em></span>, the SUBSET-SUM problem is easier than 2-PARTITION problem. Since there is no easy solution to <span class="math inline"><em>S</em><em>S</em></span> (<span class="math inline"><em>S</em><em>S</em> ∈ NP-COMPLETE</span>), there is also no easy solution to <span class="math inline"><em>2</em><em>P</em></span> and is <span class="math inline">NP-COMPLETE</span></p>
